### ISSUE TITLE
Users cannot change their vote even if setting is set to yes

### ISSUE THREAD

**Issue by oseg** [iionly/elggx_fivestar#3]
Scenario:
1. log in as an admin
2. go to administer_utilities/elggx_fivestar page
3. set "Allow users to change their votes?" to "yes"
=>Cannot change my vote on an entity

This is is a regression introduced in v2.0.1, it was working fine in v2.0.0

**Comment by iionly** [comment]
Thanks for reporting. Though I'm not sure yet how exactly it became a regression in v2.0.1 as the line of code you modified in your PR was not changed between v2.0.0 and v2.0.1. I did modify how default values of the options are handled though and this might have resulted in an unintended change.

I'll have to take a look at the code to see how to fix it best. It might not the best way to modify the settings.php action the way you suggested in your PR as the params array values are already processed before the vote change value is handled separately. Therefore, it might be better to modify the settings form mod/elggx_fivestar/views/default/admin/administer_utilities/elggx_fivestar.php instead to change 'params[change_vote]' to 'change_vote' (and maybe no longer use the params array anymore at all for the only remaining other option).

Unfortunately, I most likely won't have time to look into the issue before next week. But I will do for sure asap.
